export const en = {
  appTitle: 'Notes App',
  loginMainTitle: 'Let’s Login',
  loginAdditionalTitle: 'And notes your idea',
  createNoteTitle: 'Let’s note your idea',
  editNoteTitle: 'Edit your idea here',
  changePassword: 'Change password',
  changedPasswordMessage: 'The password was changed',
  deleteNoteTitle: 'Are you sure you want to delete note',
  settings: 'Settings',
  public: 'Public',
  tags: 'Tags',
  inputs: {
    label: {
      userName: 'User name',
      password: 'Password',
      title: 'Title',
      text: 'Text',
      tags: 'Tags',
      bgColor: 'Background color',
      newPassword: 'New password',
    },
    placeholder: {
      userName: 'Please enter username',
      password: 'Please enter password',
      title: 'Please enter note title',
      text: 'Please enter your note',
      tags: 'Please enter tags separated by comma',
      newPassword: 'Please enter new password',
    },
  },
  validation: {
    emptyFieldError: 'Please field out this field',
  },
  buttons: {
    login: 'Login',
    addNote: 'Add note',
    editNote: 'Save Changes',
    cancel: 'Cancel',
    deleteNote: 'Delete note',
    changePassword: 'Change password',
  },
  page404: {
    notFound: 'Page not found!',
    redirect: 'You will be redirected to main page in',
    sec: 'sec',
  },
  privateNote: 'This note is private. Please login first',
  back: 'Go back',
  logOut: 'Log Out',
  toPublic: 'Go to public notes',
  toPersonal: 'Go to personal notes',
}
